export const TOPICS = [
  // Ancient Civilizations — depth 9-10
  {
    eraName: "Ancient Egypt",
    category: "Ancient Civilizations",
    depthLevel: 10,
    description: "Pharaohs, pyramids, and the Nile — the world's first great civilization.",
    coreFacts: [
      "Ancient Egypt lasted over 3,000 years (3100–30 BCE)",
      "The Great Pyramid of Giza took about 20 years to build with 2.3 million stone blocks",
      "Egyptians invented one of the earliest writing systems: hieroglyphics",
      "Pharaoh Tutankhamun became king at age 9 and died at 18 or 19",
      "Cleopatra VII spoke 9 languages and was the last active ruler of Ptolemaic Egypt",
    ],
    gradeRangeMin: 5,
    gradeRangeMax: 8,
  },
  {
    eraName: "Ancient Greece",
    category: "Ancient Civilizations",
    depthLevel: 9,
    description: "City-states, democracy, philosophy, and the Olympic Games.",
    coreFacts: [
      "Greece was not one country — it was hundreds of independent city-states",
      "Athens invented democracy around 508 BCE",
      "The first Olympic Games were held in 776 BCE",
      "Socrates, Plato, and Aristotle laid the foundations of Western philosophy",
      "The Greeks used the stars to navigate and had remarkably accurate maps",
    ],
    gradeRangeMin: 5,
    gradeRangeMax: 9,
  },
  {
    eraName: "Ancient Rome",
    category: "Ancient Civilizations",
    depthLevel: 9,
    description: "Emperors, legions, aqueducts, and the greatest empire in the ancient world.",
    coreFacts: [
      "Rome grew from a small village to rule over 50 million people across three continents",
      "Roman roads were so well built that some are still in use today",
      "Julius Caesar was stabbed 23 times on March 15, 44 BCE",
      "Rome had the first apartment buildings — up to 8 stories tall",
      "The Colosseum could hold 50,000–80,000 spectators",
    ],
    gradeRangeMin: 5,
    gradeRangeMax: 10,
  },
  // Middle Ages — depth 7-8
  {
    eraName: "Medieval Europe",
    category: "Middle Ages",
    depthLevel: 8,
    description: "Knights, castles, feudalism, and the Church that shaped a continent.",
    coreFacts: [
      "Most medieval castles took 10 years or more to build",
      "Knights had to train from age 7 — first as pages, then squires, before becoming knights",
      "The Black Death killed one-third of Europe's population between 1347 and 1351",
      "Medieval people did not think the Earth was flat — educated people knew it was round",
      "Gutenberg's printing press (1440) made books affordable for the first time",
    ],
    gradeRangeMin: 6,
    gradeRangeMax: 9,
  },
  {
    eraName: "The Viking Age",
    category: "Middle Ages",
    depthLevel: 8,
    description: "Norse explorers, warriors, and settlers who reached America 500 years before Columbus.",
    coreFacts: [
      "Vikings reached North America around 1000 CE — 500 years before Columbus",
      "Viking longships could sail in as little as 1 meter of water, letting them raid rivers",
      "Not all Vikings were raiders — most were farmers, traders, and craftspeople",
      "The word 'berserk' comes from Viking warriors called berserkers",
      "Leif Erikson founded a settlement called Vinland in modern-day Newfoundland",
    ],
    gradeRangeMin: 5,
    gradeRangeMax: 9,
  },
  // Age of Exploration — depth 6-7
  {
    eraName: "Age of Exploration",
    category: "Age of Exploration",
    depthLevel: 7,
    description: "European explorers sail unknown seas, connecting — and colliding — worlds.",
    coreFacts: [
      "Columbus reached the Americas in 1492, thinking he had reached Asia",
      "Ferdinand Magellan's expedition was the first to circumnavigate the globe (1519–1522)",
      "The Aztec Empire had a population of 5–6 million and a capital bigger than London",
      "Smallpox, brought by Europeans, killed up to 90% of indigenous populations in some regions",
      "The Silk Road had connected Europe and Asia for trade long before ocean exploration",
    ],
    gradeRangeMin: 6,
    gradeRangeMax: 10,
  },
  // Revolutions — depth 4-5
  {
    eraName: "The American Revolution",
    category: "Revolutions",
    depthLevel: 5,
    description: "How thirteen colonies broke free from the British Empire and created a new nation.",
    coreFacts: [
      "The Boston Tea Party dumped 342 chests of tea worth about $1.7 million today",
      "The Declaration of Independence was adopted on July 4, 1776",
      "George Washington's army lost most of its early battles but kept fighting",
      "France secretly supported the American colonists with money, troops, and a naval fleet",
      "Thomas Jefferson wrote the Declaration in just 17 days",
    ],
    gradeRangeMin: 4,
    gradeRangeMax: 8,
  },
  {
    eraName: "The French Revolution",
    category: "Revolutions",
    depthLevel: 5,
    description: "Liberty, equality, fraternity — and a decade of radical, violent change.",
    coreFacts: [
      "The French Revolution began in 1789 and lasted until 1799",
      "King Louis XVI and Marie Antoinette were executed by guillotine in 1793",
      "The revolution killed 17,000 people officially — but 40,000+ died in the Reign of Terror",
      "Napoleon Bonaparte rose to power directly because of the revolution's chaos",
      "France was first in the world to abolish slavery — then Napoleon reinstated it",
    ],
    gradeRangeMin: 7,
    gradeRangeMax: 11,
  },
  // Modern History — depth 2-4
  {
    eraName: "World War I",
    category: "Modern History",
    depthLevel: 4,
    description: "The Great War — a new kind of industrial warfare that shattered empires.",
    coreFacts: [
      "WWI was triggered by the assassination of Archduke Franz Ferdinand in 1914",
      "Over 17 million people died — soldiers and civilians combined",
      "The trenches on the Western Front stretched 700 km from Belgium to Switzerland",
      "Soldiers on both sides declared an unofficial Christmas truce in 1914, playing soccer in no-man's-land",
      "The war introduced tanks, poison gas, airplanes, and submarines as weapons",
    ],
    gradeRangeMin: 8,
    gradeRangeMax: 12,
  },
  {
    eraName: "World War II",
    category: "Modern History",
    depthLevel: 3,
    description: "The deadliest conflict in human history — and the war that shaped the modern world.",
    coreFacts: [
      "WWII involved over 30 countries and killed an estimated 70–85 million people",
      "D-Day (June 6, 1944) was the largest seaborne invasion in history",
      "The Holocaust saw the systematic murder of 6 million Jewish people by Nazi Germany",
      "Navajo Code Talkers used their native language as an unbreakable military code",
      "The war ended in Europe on May 8, 1945 (V-E Day) and in the Pacific on September 2, 1945",
    ],
    gradeRangeMin: 8,
    gradeRangeMax: 12,
  },
  {
    eraName: "The Space Race",
    category: "Modern History",
    depthLevel: 2,
    description: "The Cold War rivalry that launched humanity into space.",
    coreFacts: [
      "The Soviet Union launched Sputnik, the first satellite, on October 4, 1957",
      "Yuri Gagarin was the first human in space, orbiting Earth on April 12, 1961",
      "Neil Armstrong and Buzz Aldrin landed on the Moon on July 20, 1969",
      "Apollo 13 suffered an oxygen tank explosion but the crew returned safely",
      "NASA's Apollo program cost about $25 billion (equivalent to $260 billion today)",
    ],
    gradeRangeMin: 4,
    gradeRangeMax: 10,
  },
  {
    eraName: "The Civil Rights Movement",
    category: "Modern History",
    depthLevel: 2,
    description: "The American struggle for racial equality that changed the nation.",
    coreFacts: [
      "Rosa Parks refused to give up her bus seat on December 1, 1955",
      "The Montgomery Bus Boycott lasted 381 days and desegregated city buses",
      "Martin Luther King Jr. delivered his 'I Have a Dream' speech to 250,000 people in Washington DC",
      "Ruby Bridges was 6 years old when she integrated an all-white school in New Orleans",
      "The Civil Rights Act of 1964 banned discrimination based on race, color, religion, or national origin",
    ],
    gradeRangeMin: 4,
    gradeRangeMax: 10,
  },
  // Very recent — depth 1
  {
    eraName: "The Digital Revolution",
    category: "Recent History",
    depthLevel: 1,
    description: "How computers, the internet, and smartphones transformed everyday life.",
    coreFacts: [
      "The World Wide Web was invented by Tim Berners-Lee in 1989",
      "The first iPhone was released in 2007 — smartphones barely existed before that",
      "By 2023, over 5 billion people use the internet — 63% of humanity",
      "Google processes over 8.5 billion searches per day",
      "Social media platforms like TikTok can reach 1 billion users faster than any technology in history",
    ],
    gradeRangeMin: 3,
    gradeRangeMax: 12,
  },
];

export const BADGES = [
  { name: "First Dive", description: "Completed your first historical topic", category: "General", icon: "🤿" },
  { name: "Ancient Civilizations Explorer", description: "Completed all Ancient Civilizations topics", category: "Ancient Civilizations", icon: "🏛️" },
  { name: "Medieval Scholar", description: "Completed all Middle Ages topics", category: "Middle Ages", icon: "⚔️" },
  { name: "Age of Exploration Adventurer", description: "Completed all Age of Exploration topics", category: "Age of Exploration", icon: "🧭" },
  { name: "Revolution Maker", description: "Completed all Revolutions topics", category: "Revolutions", icon: "✊" },
  { name: "Modern Historian", description: "Completed all Modern History topics", category: "Modern History", icon: "🌐" },
  { name: "Deep Diver", description: "Explored 5 topics across different eras", category: "General", icon: "🐋" },
  { name: "History Buff", description: "Completed 10 topics", category: "General", icon: "📚" },
  { name: "Time Traveler", description: "Completed 25 topics", category: "General", icon: "⏳" },
];
